### ISSUE TITLE
Finalize PSU student workers and what hours they're available

### ISSUE THREAD

**Issue by scholachoi** [ScienceHackDayPDX/Science-Hack-Day-PDX-2017#10]
"Kason O’Connor will be working with Alex helping out in the hardware area and getting things from the machine shop from 9:00AM-5PM Saturday, and from 9am-2pm Sunday. I [Alex?] may pay him for an extra shift on Friday depending on what help I need with load in and load out."

**Comment by jmicrobe** [comment]
We had some great volunteers! Closing this.
