### ISSUE TITLE
Identify team captains

### ISSUE THREAD

**Issue by scholachoi** [ScienceHackDayPDX/Science-Hack-Day-PDX-2017#11]

**Comment by scholachoi** [comment]
- [ ] Hardware support - Chris and Alex
- [ ] Software - Lilly, Max, Ivor

**Comment by jmicrobe** [comment]
Based on discussions on the 8/31 mtg notes gdrive doc looks like we've assigned folks in charge of organizing & managing the various areas. closing this!
