### ISSUE TITLE
SHD2017 MEALS! 🍕

### ISSUE THREAD

**Issue by jmicrobe** [ScienceHackDayPDX/Science-Hack-Day-PDX-2017#5]
Here are meals (and supplies) we need to have covered for SHD 2017:

# Saturday
- [x] bevs (all day)
   - [x] coffee
   - [x] kombucha
   - [ ] sparkling water?
- [ ] snacks (all day)
- [x] breakfast 
- [ ] lunch
- [x] dinner

# Sunday
- [ ] coffee & bevs
- [ ] breakfast
- [ ] lunch/end of event meal

# Supplies
- [ ] plates
- [ ] utensils
- [ ] napkins
- [ ] coolers for beverages
- [ ] cups? 

As we get meals set up we can check off this list and add comments to this issue with details.

**Comment by daniellecrobinson** [comment]
I have just confirmed dinner order with catering. I need to go **pick it up in person** at 4pm at World Foods at Everett 830 NW Everett 503-802-0755

1 Hummus Large
 1 Baba Ghanouj Large
1 Falafel with Tahini Large
1 Vegetarian Tapas Platter Large (no falafel, sub grape leaves)
1 Fattoush Salad
1 Lacinato Kale Salad
2 Kabob Skewers Dozen
1 Lebanese Pastry Platter Large

total cost is 496.00 and Mozilla Corp will reimburse me

**Comment by daniellecrobinson** [comment]
Foxy Coffee confirmed 5 gal of cold brew, pickup on 9/7 or early on 9/9

**Comment by jmicrobe** [comment]
Thanks for picking stuff up you guys, and grabbing some last minute food!
