### ISSUE TITLE
Youth Zone

### ISSUE THREAD

**Issue by rchampieux** [ScienceHackDayPDX/Science-Hack-Day-PDX-2017#6]
SHD PDX 2017 will include an expanded youth zone with dedicated projects, supplies, and facilitators.

**Comment by rchampieux** [comment]
- [x] Identify dedicated projects, spanning age cohorts.
- [x] Identify youth zone supplies
- [x] Confirm organizer / volunteer facilitators and facilitator schedule.
- [x] Create Youth zone signage.
- [x] Identify and contact Youth Zone outreach targets.
- [x] Finalize supplies
- [x] Finalize featured activities
- [x] Finalize shifts
- [x] Pick up library stuff (Lilly)

**Comment by scholachoi** [comment]
Daniela and Jess will work on this task along with Merrit and Rachael.
